# Normalización
NORMALIZATION_FACTOR = 255.0

# División del dataset
TRAIN_RATIO = 0.7
VAL_RATIO = 0.15
TEST_RATIO = 0.15

# Dimensiones de imagen
IMAGE_HEIGHT = 28
IMAGE_WIDTH = 28
IMAGE_SIZE = IMAGE_HEIGHT * IMAGE_WIDTH

# Clases posibles
NUM_CLASSES = 49

# Entrenamiento
DEFAULT_LR = 0.01
DEFAULT_EPOCHS = 5000
DEFAULT_BATCH_SIZE = None
DEFAULT_PATIENCE = 20
DEFAULT_USE_ADAM = False
DEFAULT_BETA1 = 0.9
DEFAULT_BETA2 = 0.999
DEFAULT_USE_BATCHNORM = False
DEFAULT_DROPOUT_RATE = 0.0
DEFAULT_L2_LAMBDA = 0.0
DEFAULT_SCHEDULER_TYPE = None
DEFAULT_FINAL_LR = None
DEFAULT_EARLY_STOPPING = True
DEFAULT_LAYER_SIZES = [784, 100, 80, 49]

#ramdom seed
RANDOM_SEED = 42

#hparams file path
HYPERPARAMS_FILE = "hparams.csv"